UPD_FROMBLOB = b"\x40"
UPD_FROMBLOBNEXT = b"\x41"
UPD_FROMPAULA = b"\x01"
CMD_REQUEST = b"\x50"
CMD_REQUEST_SUCCESS = b"\x51"




RELATIVE_ADRESS_THRESHOLD = 0xFFffFFff


from pwn import asm
SYSCALL_INSTR= asm("syscall")